ui.url=https://demowebshop.tricentis.com
chrome_username=mounyajavvadi@gmail.com
chrome_password=Mounya@123
firefox_username=narijavvadi@gmail.com
firefox_password=Nari@123
edge_username=gst6300@gmail.com
edge_password=Ganesh@123

api.baseUrl=https://fakestoreapi.com
api.username=mor_2314
api.password=83r5^_